version: '3.9'
services:
  pytop:
    restart: always
    image: ichiharanaruki/pytop:latest
    container_name: 'pytop-container'
    working_dir: '/home/usr/mounted/'
    tty: true
    volumes:
      - ./:/home/usr/mounted
    shm_size: 4gb
    environment:
      - DISPLAY=host.docker.internal:0.0
