# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application - run and test

on:
  push:
    branches: [ "main", "feature/mainstream" ]
  pull_request:
    types: [opened, reopened]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up container
      run: |
       docker pull docker.io/ichiharanaruki/pytop:latest
       docker-compose up -d
    - name: Test with pytest
      run: |
        docker-compose exec -T -w /home/usr/mounted pytop pytest
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pdoc3
    - name: Generate documentation
      run: |
        pdoc --html pytop --output-dir docs
        mv docs/pytop/* docs/
        rmdir docs/pytop
